name: flutter_widget_from_html_core
version: 0.15.3
description: Flutter package to render html as widgets that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  flutter: ">=3.10.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  csslib: ">=0.17.0 <2.0.0"
  flutter:
    sdk: flutter
  html: ^0.15.0
  image_network: 2.5.6
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  lint: any
  test: any


